#+TITLE: Weihnachtsgeschichte 2025
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css">
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


#+BEGIN_EXPORT html
<a href="index.pdf" download="Weihnachtsgeschichte.pdf">PDF herunterladen</a>
#+END_EXPORT

* Einleitung
  Hallo liebe Leute und frohe Weihnachten! Das ist cool again.

  Die kleine Tanne und der Stern

  In einem verschneiten Wald stand eine kleine Tanne, die war noch
  jung und viel kleiner als die anderen Bäum   e. Jeden Winter sah sie,
  wie die großen Tannen freudig geschmückt wurden und die Tiere unter
  ihren Zweigen Weihnachten feierten. Die kleine Tanne wünschte sich
  nichts sehnlicher, als auch einmal Teil des Festes zu sein.

  Am Heiligabend schien ein besonders heller Stern am Himmel. Er sah
  die kleine Tanne und bemerkte ihren bescheidenen Wunsch. Da ließ der
  Stern einen warmen Lichtstrahl auf die Tanne fallen. Das ganze
  Waldstück leuchtete auf, und plötzlich kamen alle Tiere aus ihren
  Verstecken und versammelten sich um die Tanne.

  Sie schmückten sie mit kleinen Äpfeln, Nüssen und bunten Bändern,
  die sie im Wald fanden. Die kleine Tanne leuchtete durch das
  Sternenlicht so hell wie nie zuvor. Sie fühlte sich glücklich, denn
  sie war endlich der Mittelpunkt des Weihnachtsfestes.

  Und seitdem steht jedes Jahr eine kleine, leuchtende Tanne im Herzen
  des Waldes – und der Stern wacht über sie von oben.
