#+TITLE: Weihnachtsgeschichte 2020
#+AUTHOR: von mir, Simon

#+INCLUDE: header.org
#+INCLUDE: vorwort.org
* Corona-Chronicles

\cb{D}ie Sonne knallt durch die Schlitze in der Schalousie und voll in
mein Gesicht. Das Schnarchen legt sich, die Augen öffnen sich
verschlafen und das begleitet von Knarzen und Quietschen des
Bettgestells verlässt der Prinz die Schlafstatt. Der Wecker springt an
und dudelt drauf los, wie kann man so früh so eine gute Laune haben?
Da mein Wecker gleichzeitig als Smartphone dient unterdrücke ich das
obligatorische /An-die-Wand-werfen/ und schleppe mich stattdessen ins
Bad. /Brrrr/ \dots der kleine Raum ist arschkalt und das Wasser in der
Dusche will auch nicht warm werden. Nächste Station Kalender, Gestern
durchstreichen. Dann zum Kaffeekochen, Brotzeit richten und ab mit dem
Essen und der Thermoskanne Kaffee in den Rucksack. Los gehts,
Schlüssel, Jacke, Kopfhörer, Podcast, Spotify. Ich verlasse das Haus,
das ist jeden Morgen ein großer Spaß. Erst muss ich eine Zwischentür
aufschließen, die mein Nachbar netterweise zugesperrt hat. Nur damit
ich sie wieder aufsperren kann, toll. Dann mit dem zweiten Schlüssel
das Hoftor aufschließen, könnte ja sein das irgendwer das uns wer
klaut! Hach ja, und dann geht es auf dem Weg in die Arbeit. Ich
verlasse das Haus Richtung S-Bahn, gehe 10 meter, drehe auf der Stelle
um und gehe zurück nach Hause. Juhu ein weiterer Tag im
Homeoffice. \newline

\noindent Mein Telefon klingelt, es ist mein Boss. Nach ca. 1
$\frac{1}{2}$ Stunden kommt bei mir langsam das Gefühl auf das mein Boss
nur mit jemand reden möchte und gar keinen Auftrag hat. Der Wecker
klingelt, es ist Mittagspause. Ich hab jetzt keinen Bock auf meine
sorgfältig gerichteten Brote und schieb eine Pizza in den
Offen. Gerade als die fertig ist und ich mir ein herzhaftes Stück
genehmigen möchte trudelt eine Mail in meinen Postfach ein. Und wie
sollte es auch anderes sein, gleich die nächste und die nächste. Geil!
Dann springt auch schon der nächste Wecker an - jetzt beginnt die
Online Vorlesung - klar, dafür hab ich ja grade Zeit. Es ist zum
Verückt werden. Die Pizza wird kalt, und meine Laune noch
schlechter. Die Mails sind von meinem Lieblingskunden, das ist der,
immer Recht hat, an nichts selber Schuld ist und wenn man ihm dann
erklärt und gezeigt hat das er doch Schuld ist sich noch nicht mal
entschuldigt. Einmal hatten wir das Problem mit ihm das, dass Programm
so /komisch/ aussieht. Ende vom Lied, er hat es fertig bekommen
Windows 95 auf seinem Rechner zu installieren - /weil das neue Windows
mag ich nicht/ - und prompt strotzte das Ding von Virren und allem was
man nur will wenn man auf Schmerz und Erniedrigung steht. Aber
natürlich war das nicht seine Schuld \dots\newline

\noindent Die Mails mit denen er mir jetzt den Appetit und die Laune
verdirbt klingen nach einem klassischen Fall von /Have you tried to
turn it of and on again?/ Als ich ihm um selbiges bitte kommt keine
Antwort, dass kann man nun entweder so deuten dass er den Rechner
nicht mehr anbekommt, oder dass das Problem damit gelöst
ist. Endlich - Piz \dots oder auch nicht schon die nächste Mail. Und
dieses Mal sogar mit einem echten Problem. Wie sollte es auch anderes
sein natürlich eines von diesen Problemen, die nur der spezielle
Betreuer dieses speziellen Projekts lösen kann. Der ist natürlich
gerade auf keinem der Kanäle erreichbar und der Kunde schiebt Panik,
hoffentlich ist bald Feierabend \dots\newline

\noindent Kalte Pizza ist besser als kalter Kaffe. Ich schalte mir
eine Episode Rick and Morty ein und kucke vorsichtig auf den
Arbeitskalender. Einen kurzen Moment will ich mich schon freuen - für
die Woche wars das erstmal, aber da ist ja auch noch die Uni und
außerdem lauert draußen vor der Tür der Spielverderber. Ich bin total
urlaubsreif. Geschäftsidee: Strand für Zuhause, Meer fürs Wohnzimmer. 
Ich wechsle zu Youtube und schalte die größten Summerhits 2006 ein,
setze eine Sonnenbrille auf und schlürfe meine Kaffee. Kalter Kaffee
macht ja angeblich hübsch. Entweder ist das Quatsch, oder ich bin
Wunderschön - nur hat Kaffee dann wohl andere als die allgemein
akzeptierten Schönheitsideale. Ich überlege kurz ob man sich online
Cocktails bestellen kann. Lachend tippe ich es in die Suchmachine
ein. Nach etwas Recherche komme ich von ~Cocktail-to-go~ über
~Summerfeeling for home musik~ auf ein komisches Angebot auf
Ebay. Eine Versteigerung, die nur noch wenige Minuten läuft biete
sogenannte /Urlaubstropfen/ an. In der Beschreibung behauptet der
Verkäufer, das jedes der im Set enthaltenen Fläschen einen mindestens
20 stündigen Trip zu einem beliebigen Reise ziel beinhaltet. In den
Bildern findet sich auch eine Bedienungsanweisung. In den Fläschen ist
jeweils eine Pipette, mit der man dann 3-5 Tropfen in ein Heißgetränk
träufelt. Der letzte Schritt ist eine Cartoonzeichnung von einem
Menschen mit Spiralen als Augen. Ich Lache und biete 50ct mehr als das
aktuelle Gebot. Dann gehts ab ins Bett.
* Die Lieferung
An diesem Tag reißt mich nicht mein Wecker, oder ein Sonnenstrahl aus
dem Land der Träume. Ein lautes Schrillen verkündet, das jemand am
Hoftor meine Klingel gedrückt hat. Ich stehe Kerzengerade im Bett. Das
Läuten ist so laut - das hat vermutlich ein Schwerhöriger eingestellt.
Am Hoftor angekommen erwische ich den Paketdienst gerade noch. Etwas
verdattert packe ich das Ebay paket aus. Scheinbar hat mich gestern
keiner mehr überboten. Darin sind 6 braune Fläschen mit von Hand
aufgeklebten Etiketten. Meine Kehle wird trocken, ich hab doch nicht
etwa versehentlich im Internet Drogen gekauft? Nervös masiere ich
meine Augen.
* Abenteuer 2
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. 
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of
the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown
printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into
electronic typesetting, remaining essentially unchanged. It was
popularised in the 1960s with the release of Letraset sheets
containing Lorem Ipsum passages, and more recently with desktop
publishing software like Aldus PageMaker including versions of Lorem
Ipsum. 
* Abenteuer 3
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. 
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of
the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown
printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into
electronic typesetting, remaining essentially unchanged. It was
popularised in the 1960s with the release of Letraset sheets
containing Lorem Ipsum passages, and more recently with desktop
publishing software like Aldus PageMaker including versions of Lorem
Ipsum. 
* Abenteuer 4
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. 
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of
the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown
printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into
electronic typesetting, remaining essentially unchanged. It was
popularised in the 1960s with the release of Letraset sheets
containing Lorem Ipsum passages, and more recently with desktop
publishing software like Aldus PageMaker including versions of Lorem
Ipsum. 
* Guten Morgen
Ein Sonnenstrahl sticht durch die Schalousie und genau in mein
Gesicht. Ich wälze mich unwillig hin- und her. Mein Wecker springt
an. Mit er fröhlichkeit eines Elektrischen Geräts, das weiß dass es
niemals gegen eine Wand geworfen werden wird, dudelt mein Smartphone
vor sich hin. Ich ächze mich aus der Horizontalen und schalte die
Nervensäge aus. Badezimmer, Brotzeit richten, Kaffeekochen. Ach ja den
Kalender hab ich vergessen. Ich schlürfe zur Wohnungstür, an der der
Kalender hängt, setze den Stift an und halte abrubt inne. Heute ist
Freitag? Ich drehe mich ruckartig um auf meinem Schreibtisch ist weder
eine Spur von einem Paket noch von den Fläschen, die ich in den
letzten Tagen durch probiert habe. Ich drehe mich wieder zum
Kalender. Mein Handy! Welches Datum ist es heute? Es ist Freitag. Ich
sinke verwirrt auf dem Bürostuhl zusammen. Dann muss ich smunzeln. Mit
einem Druck auf den Einschaltknopf an meinem Computer wacht der
Rechner auf. Es dauert einen Moment bis sich der Bildschirm
einschaltet. Ebay ist immer noch offen, ich habe die Auktion
verloren. Unmittelbar nach meinem Angebot ist das Angebot des
vorherigen Höchstbietenden um 1Euro erhöht worden. Ich klicke auf die
Kurzfassung der Beschreibung. Die Seite scrollt runter. Gut das ich
die Auktion nicht gewonnen hab - Dieser /Scherzartikel/ beinhaltet 6
Flaschen mit durch Lebensmittelfarbe eingefärbten nicht alkoholischen
Inhalt. Ungefährlich für Kinder und Haustiere. \newline

\noindent Zeit für ein Frühstück. Die Pausebrote schmecken nur
bedingt. Ich drehe mich nochmal zum Kalender um. Hoffentlich ist bald 
Weihnachten, dann gibts endlich wieder was vernünftiges zu Essen.

#+BEGIN_CENTER
Ich wünsche dir jetzt schöne Weihnachten und einen guten\\
Rutsch in das neue Jahr. Diese Jahr ist das Motto:\\
/Es kann nur besser werden!/
#+END_CENTER
